### ISSUE TITLE
Chef client version support

### ISSUE THREAD

**Issue by aspyatkin** [sous-chefs/postgresql#679]
According to README and metadata, this cookbook is supposed to work on Chef 13.8+. Although it will not, since all resources have been rewritten and from now on make use of Chef 16+ `provides` without a fallback `resource_name` for older clients.

Either documentation or resources' code should be updated so that a user of an older Chef client won't be misdirected with the cryptic `FATAL: NoMethodError: undefined method `[]' for nil:NilClass`.

**Comment by ramereth** [comment]
I'm not able to reproduce this problem using the latest version of this cookbook. All of the various kitchen suites work with Chef 13.8.
1. What version of the cookbook are you using that is causing this problem?
2. What version of Chef are you using that's causing the problem?

**Comment by aspyatkin** [comment]
Well, I was using Chef 15.12.22 and latest version of this cookbook, but it seems to me that I'd made a mistake in my configuration with `action [:create, :install]` in `postgresql_server_install` (instead of `action [:install, :create]`) which in turn leads to issues related to inexistent `node.run_state['postgresql']['version']`. The error message is although very similar to those I get when I use some cookbooks which are exclusively Chef 16+, which confused me a little and I thought it had something to do with missing `resource_name`.

Thank you for your time verifying the case.
